spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    password: postgres
    platform: postgres
    url: jdbc:postgresql://localhost:5432/database
    driverClassName: org.postgresql.Driver
server:
  port: 8080
