spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: Reqz8AMW
    platform: postgres
    url: jdbc:postgresql://localhost:5432/nimosini
    driverClassName: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        web: DEBUG

rabbitmq:
  queue:
    name: queueName
  exchange:
    name: exchangeName
  routing-key: routingKey
