ifood:
  production:
    merchantApiHost: "https://merchant-api.ifood.com.br"
    clientId: "clientId"
    clientSecret: "clientSecret"
    merchantId: "merchantId"
    eventPollingDelayMilliseconds: 30000

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
